name: flutter_api_helper
description: "A powerful, easy-to-use API helper for Flutter that handles everything from simple GET requests to complex error handling, caching, and token management."

publish_to: https://pub.dev

version: 1.0.0

homepage: https://webzdigitalmarketing.pk/
repository: https://github.com/ranahammad7/flutter_api_helper
issue_tracker: https://github.com/ranahammad7/flutter_api_helper/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
